### ISSUE TITLE
Update the command args enum to include aliases as part of each enum value

### ISSUE THREAD

**Issue by jmakhack** [jmakhack/hydrate-reminder#113]
## Task Context

Currently, the `HydrateReminderCommandArgs` enum found in `src/main/java/com/hydratereminder/HydrateReminderCommandArgs.java` has a separate enum value for both command names and command aliases.
This task is to have both the command name and alias be combined into the same enum value.

For example, `NEXT("next")` and `N("n")` should not be separate enum values.
Instead, they should be combined into a single enum value: `NEXT("next", "n")`.

This needs to be done for all commands: `NEXT`, `PREV`, `RESET`, `HELP`, `TOTAL`

The `toString()` method should work as it currently does.
For example, `NEXT.toString()` should still return `"next"`.

No new methods need to be added as part of this task.
Implementing the method to retrieve the aliases will be done in a separate issue.

## Additional Context

The following tasks need to be completed in order for this issue to be considered completed:
- [x] Update all enum values in `HydrateReminderCommandArgs` to contain their respective aliases
- [x] Ensure the `toString()` method has not changed in functionality
- [x] Update the unit test in `src/test/java/com/hydratereminder/HydrateReminderCommandArgsTest.java`

## Hacktoberfest Details

I will assign this issue to the first person who comments on this issue.
They will be given 48 hours to create a pull request before I allow others to take on this issue.
All other pull requests will be marked as spam and ignored.

This issue will only be assigned to those participating in the ongoing Hacktoberfest event (until it is over).
Each participant will only be allowed to pick up one issue in this project to give others the opportunity to participate as well.

Feel free to ask any clarifying questions or for any help in the comments below.
